package au.edu.uts.eng.remotelabs.schedserver.dataaccess.entities;

// Generated 06/01/2010 5:09:20 PM by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RequestCapabilities generated by hbm2java
 */
@Entity
@Table(name = "request_capabilities", catalog = "sahara")
public class RequestCapabilities implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -4070925552271023590L;
    private Long id;
    private String capabilities;
    private Set<ResourcePermission> resourcePermissions = new HashSet<ResourcePermission>(
            0);
    private Set<MatchingCapabilities> matchingCapabilitieses = new HashSet<MatchingCapabilities>(
            0);
    private Set<ResourcePermission> resourcePermissions_1 = new HashSet<ResourcePermission>(
            0);
    private Set<MatchingCapabilities> matchingCapabilitieses_1 = new HashSet<MatchingCapabilities>(
            0);

    public RequestCapabilities()
    {
    }

    public RequestCapabilities(final String capabilities)
    {
        this.capabilities = capabilities;
    }

    public RequestCapabilities(final String capabilities,
            final Set<ResourcePermission> resourcePermissions,
            final Set<MatchingCapabilities> matchingCapabilitieses,
            final Set<ResourcePermission> resourcePermissions_1,
            final Set<MatchingCapabilities> matchingCapabilitieses_1)
    {
        this.capabilities = capabilities;
        this.resourcePermissions = resourcePermissions;
        this.matchingCapabilitieses = matchingCapabilitieses;
        this.resourcePermissions_1 = resourcePermissions_1;
        this.matchingCapabilitieses_1 = matchingCapabilitieses_1;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(final Long id)
    {
        this.id = id;
    }

    @Column(name = "capabilities", nullable = false, length = 65535)
    public String getCapabilities()
    {
        return this.capabilities;
    }

    public void setCapabilities(final String capabilities)
    {
        this.capabilities = capabilities;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "requestCapabilities")
    public Set<ResourcePermission> getResourcePermissions()
    {
        return this.resourcePermissions;
    }

    public void setResourcePermissions(
            final Set<ResourcePermission> resourcePermissions)
    {
        this.resourcePermissions = resourcePermissions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "requestCapabilities")
    public Set<MatchingCapabilities> getMatchingCapabilitieses()
    {
        return this.matchingCapabilitieses;
    }

    public void setMatchingCapabilitieses(
            final Set<MatchingCapabilities> matchingCapabilitieses)
    {
        this.matchingCapabilitieses = matchingCapabilitieses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "requestCapabilities")
    public Set<ResourcePermission> getResourcePermissions_1()
    {
        return this.resourcePermissions_1;
    }

    public void setResourcePermissions_1(
            final Set<ResourcePermission> resourcePermissions_1)
    {
        this.resourcePermissions_1 = resourcePermissions_1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "requestCapabilities")
    public Set<MatchingCapabilities> getMatchingCapabilitieses_1()
    {
        return this.matchingCapabilitieses_1;
    }

    public void setMatchingCapabilitieses_1(
            final Set<MatchingCapabilities> matchingCapabilitieses_1)
    {
        this.matchingCapabilitieses_1 = matchingCapabilitieses_1;
    }

}
