package au.edu.uts.eng.remotelabs.schedserver.dataaccess.entities;

// Generated 06/01/2010 5:09:20 PM by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Rig generated by hbm2java
 */
@Entity
@Table(name = "rig", catalog = "sahara", uniqueConstraints = {
        @UniqueConstraint(columnNames = "type_id"),
        @UniqueConstraint(columnNames = "caps_id"),
        @UniqueConstraint(columnNames = "session_id"),
        @UniqueConstraint(columnNames = "name") })
public class Rig implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -2028175400491809280L;
    private Long id;
    private RigType rigType;
    private Session session;
    private RigCapabilities rigCapabilities;
    private String name;
    private String contactUrl;
    private Date lastUpdateTimestamp;
    private boolean online;
    private boolean inSession;
    private boolean active;
    private Set<ResourcePermission> resourcePermissions = new HashSet<ResourcePermission>(
            0);
    private Set<Session> sessions = new HashSet<Session>(0);
    private Set<Session> sessions_1 = new HashSet<Session>(0);
    private Set<ResourcePermission> resourcePermissions_1 = new HashSet<ResourcePermission>(
            0);

    public Rig()
    {
    }

    public Rig(final RigType rigType, final RigCapabilities rigCapabilities,
            final String name, final String contactUrl,
            final Date lastUpdateTimestamp, final boolean online,
            final boolean inSession, final boolean active)
    {
        this.rigType = rigType;
        this.rigCapabilities = rigCapabilities;
        this.name = name;
        this.contactUrl = contactUrl;
        this.lastUpdateTimestamp = lastUpdateTimestamp;
        this.online = online;
        this.inSession = inSession;
        this.active = active;
    }

    public Rig(final RigType rigType, final Session session,
            final RigCapabilities rigCapabilities, final String name,
            final String contactUrl, final Date lastUpdateTimestamp,
            final boolean online, final boolean inSession,
            final boolean active,
            final Set<ResourcePermission> resourcePermissions,
            final Set<Session> sessions, final Set<Session> sessions_1,
            final Set<ResourcePermission> resourcePermissions_1)
    {
        this.rigType = rigType;
        this.session = session;
        this.rigCapabilities = rigCapabilities;
        this.name = name;
        this.contactUrl = contactUrl;
        this.lastUpdateTimestamp = lastUpdateTimestamp;
        this.online = online;
        this.inSession = inSession;
        this.active = active;
        this.resourcePermissions = resourcePermissions;
        this.sessions = sessions;
        this.sessions_1 = sessions_1;
        this.resourcePermissions_1 = resourcePermissions_1;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(final Long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "type_id", unique = true, nullable = false)
    public RigType getRigType()
    {
        return this.rigType;
    }

    public void setRigType(final RigType rigType)
    {
        this.rigType = rigType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "session_id", unique = true)
    public Session getSession()
    {
        return this.session;
    }

    public void setSession(final Session session)
    {
        this.session = session;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "caps_id", unique = true, nullable = false)
    public RigCapabilities getRigCapabilities()
    {
        return this.rigCapabilities;
    }

    public void setRigCapabilities(final RigCapabilities rigCapabilities)
    {
        this.rigCapabilities = rigCapabilities;
    }

    @Column(name = "name", unique = true, nullable = false, length = 50)
    public String getName()
    {
        return this.name;
    }

    public void setName(final String name)
    {
        this.name = name;
    }

    @Column(name = "contact_url", nullable = false, length = 65535)
    public String getContactUrl()
    {
        return this.contactUrl;
    }

    public void setContactUrl(final String contactUrl)
    {
        this.contactUrl = contactUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_timestamp", nullable = false, length = 19)
    public Date getLastUpdateTimestamp()
    {
        return this.lastUpdateTimestamp;
    }

    public void setLastUpdateTimestamp(final Date lastUpdateTimestamp)
    {
        this.lastUpdateTimestamp = lastUpdateTimestamp;
    }

    @Column(name = "online", nullable = false)
    public boolean isOnline()
    {
        return this.online;
    }

    public void setOnline(final boolean online)
    {
        this.online = online;
    }

    @Column(name = "in_session", nullable = false)
    public boolean isInSession()
    {
        return this.inSession;
    }

    public void setInSession(final boolean inSession)
    {
        this.inSession = inSession;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(final boolean active)
    {
        this.active = active;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rig")
    public Set<ResourcePermission> getResourcePermissions()
    {
        return this.resourcePermissions;
    }

    public void setResourcePermissions(
            final Set<ResourcePermission> resourcePermissions)
    {
        this.resourcePermissions = resourcePermissions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rig")
    public Set<Session> getSessions()
    {
        return this.sessions;
    }

    public void setSessions(final Set<Session> sessions)
    {
        this.sessions = sessions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rig")
    public Set<Session> getSessions_1()
    {
        return this.sessions_1;
    }

    public void setSessions_1(final Set<Session> sessions_1)
    {
        this.sessions_1 = sessions_1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rig")
    public Set<ResourcePermission> getResourcePermissions_1()
    {
        return this.resourcePermissions_1;
    }

    public void setResourcePermissions_1(
            final Set<ResourcePermission> resourcePermissions_1)
    {
        this.resourcePermissions_1 = resourcePermissions_1;
    }

}
