package au.edu.uts.eng.remotelabs.schedserver.dataaccess.entities;

// Generated 06/01/2010 5:09:20 PM by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RigType generated by hbm2java
 */
@Entity
@Table(name = "rig_type", catalog = "sahara")
public class RigType implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -3717782764245485528L;
    private Long id;
    private String name;
    private int logoffGraceDuration;
    private boolean codeAssignable;
    private Set<ResourcePermission> resourcePermissions = new HashSet<ResourcePermission>(
            0);
    private Set<Rig> rigs = new HashSet<Rig>(0);
    private Set<Rig> rigs_1 = new HashSet<Rig>(0);
    private Set<ResourcePermission> resourcePermissions_1 = new HashSet<ResourcePermission>(
            0);

    public RigType()
    {
    }

    public RigType(final String name, final int logoffGraceDuration,
            final boolean codeAssignable)
    {
        this.name = name;
        this.logoffGraceDuration = logoffGraceDuration;
        this.codeAssignable = codeAssignable;
    }

    public RigType(final String name, final int logoffGraceDuration,
            final boolean codeAssignable,
            final Set<ResourcePermission> resourcePermissions,
            final Set<Rig> rigs, final Set<Rig> rigs_1,
            final Set<ResourcePermission> resourcePermissions_1)
    {
        this.name = name;
        this.logoffGraceDuration = logoffGraceDuration;
        this.codeAssignable = codeAssignable;
        this.resourcePermissions = resourcePermissions;
        this.rigs = rigs;
        this.rigs_1 = rigs_1;
        this.resourcePermissions_1 = resourcePermissions_1;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(final Long id)
    {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 50)
    public String getName()
    {
        return this.name;
    }

    public void setName(final String name)
    {
        this.name = name;
    }

    @Column(name = "logoff_grace_duration", nullable = false)
    public int getLogoffGraceDuration()
    {
        return this.logoffGraceDuration;
    }

    public void setLogoffGraceDuration(final int logoffGraceDuration)
    {
        this.logoffGraceDuration = logoffGraceDuration;
    }

    @Column(name = "code_assignable", nullable = false)
    public boolean isCodeAssignable()
    {
        return this.codeAssignable;
    }

    public void setCodeAssignable(final boolean codeAssignable)
    {
        this.codeAssignable = codeAssignable;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rigType")
    public Set<ResourcePermission> getResourcePermissions()
    {
        return this.resourcePermissions;
    }

    public void setResourcePermissions(
            final Set<ResourcePermission> resourcePermissions)
    {
        this.resourcePermissions = resourcePermissions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rigType")
    public Set<Rig> getRigs()
    {
        return this.rigs;
    }

    public void setRigs(final Set<Rig> rigs)
    {
        this.rigs = rigs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rigType")
    public Set<Rig> getRigs_1()
    {
        return this.rigs_1;
    }

    public void setRigs_1(final Set<Rig> rigs_1)
    {
        this.rigs_1 = rigs_1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rigType")
    public Set<ResourcePermission> getResourcePermissions_1()
    {
        return this.resourcePermissions_1;
    }

    public void setResourcePermissions_1(
            final Set<ResourcePermission> resourcePermissions_1)
    {
        this.resourcePermissions_1 = resourcePermissions_1;
    }

}
