package au.edu.uts.eng.remotelabs.schedserver.dataaccess.entities;

// Generated 06/01/2010 5:09:20 PM by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "sahara")
public class Session implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -4636136114987299334L;
    private Long id;
    private User user;
    private ResourcePermission resourcePermissionByResourcePermissionId;
    private ResourcePermission resourcePermissionByResourcePermissionId_1;
    private Rig rig;
    private String userName;
    private String userNamespace;
    private Date requestTime;
    private String resourceType;
    private Long requestedResourceId;
    private String requestedResourceName;
    private short priority;
    private Date activityLastUpdated;
    private String assignedRigName;
    private Date assignmentTime;
    private boolean active;
    private Date removalTime;
    private String removalReason;
    private String codeReference;
    private short extensions;
    private Set<Rig> rigs = new HashSet<Rig>(0);
    private Set<Rig> rigs_1 = new HashSet<Rig>(0);

    public Session()
    {
    }

    public Session(final String userName, final String userNamespace,
            final Date requestTime, final String resourceType,
            final String requestedResourceName, final short priority,
            final Date activityLastUpdated, final String assignedRigName,
            final Date assignmentTime, final boolean active,
            final Date removalTime, final String removalReason,
            final String codeReference, final short extensions)
    {
        this.userName = userName;
        this.userNamespace = userNamespace;
        this.requestTime = requestTime;
        this.resourceType = resourceType;
        this.requestedResourceName = requestedResourceName;
        this.priority = priority;
        this.activityLastUpdated = activityLastUpdated;
        this.assignedRigName = assignedRigName;
        this.assignmentTime = assignmentTime;
        this.active = active;
        this.removalTime = removalTime;
        this.removalReason = removalReason;
        this.codeReference = codeReference;
        this.extensions = extensions;
    }

    public Session(
            final User user,
            final ResourcePermission resourcePermissionByResourcePermissionId,
            final ResourcePermission resourcePermissionByResourcePermissionId_1,
            final Rig rig, final String userName, final String userNamespace,
            final Date requestTime, final String resourceType,
            final Long requestedResourceId, final String requestedResourceName,
            final short priority, final Date activityLastUpdated,
            final String assignedRigName, final Date assignmentTime,
            final boolean active, final Date removalTime,
            final String removalReason, final String codeReference,
            final short extensions, final Set<Rig> rigs, final Set<Rig> rigs_1)
    {
        this.user = user;
        this.resourcePermissionByResourcePermissionId = resourcePermissionByResourcePermissionId;
        this.resourcePermissionByResourcePermissionId_1 = resourcePermissionByResourcePermissionId_1;
        this.rig = rig;
        this.userName = userName;
        this.userNamespace = userNamespace;
        this.requestTime = requestTime;
        this.resourceType = resourceType;
        this.requestedResourceId = requestedResourceId;
        this.requestedResourceName = requestedResourceName;
        this.priority = priority;
        this.activityLastUpdated = activityLastUpdated;
        this.assignedRigName = assignedRigName;
        this.assignmentTime = assignmentTime;
        this.active = active;
        this.removalTime = removalTime;
        this.removalReason = removalReason;
        this.codeReference = codeReference;
        this.extensions = extensions;
        this.rigs = rigs;
        this.rigs_1 = rigs_1;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(final Long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    public User getUser()
    {
        return this.user;
    }

    public void setUser(final User user)
    {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resource_permission_id")
    public ResourcePermission getResourcePermissionByResourcePermissionId()
    {
        return this.resourcePermissionByResourcePermissionId;
    }

    public void setResourcePermissionByResourcePermissionId(
            final ResourcePermission resourcePermissionByResourcePermissionId)
    {
        this.resourcePermissionByResourcePermissionId = resourcePermissionByResourcePermissionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resource_permission_id", insertable = false, updatable = false)
    public ResourcePermission getResourcePermissionByResourcePermissionId_1()
    {
        return this.resourcePermissionByResourcePermissionId_1;
    }

    public void setResourcePermissionByResourcePermissionId_1(
            final ResourcePermission resourcePermissionByResourcePermissionId_1)
    {
        this.resourcePermissionByResourcePermissionId_1 = resourcePermissionByResourcePermissionId_1;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_rig_id")
    public Rig getRig()
    {
        return this.rig;
    }

    public void setRig(final Rig rig)
    {
        this.rig = rig;
    }

    @Column(name = "user_name", nullable = false, length = 50)
    public String getUserName()
    {
        return this.userName;
    }

    public void setUserName(final String userName)
    {
        this.userName = userName;
    }

    @Column(name = "user_namespace", nullable = false, length = 50)
    public String getUserNamespace()
    {
        return this.userNamespace;
    }

    public void setUserNamespace(final String userNamespace)
    {
        this.userNamespace = userNamespace;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "request_time", nullable = false, length = 19)
    public Date getRequestTime()
    {
        return this.requestTime;
    }

    public void setRequestTime(final Date requestTime)
    {
        this.requestTime = requestTime;
    }

    @Column(name = "resource_type", nullable = false, length = 5)
    public String getResourceType()
    {
        return this.resourceType;
    }

    public void setResourceType(final String resourceType)
    {
        this.resourceType = resourceType;
    }

    @Column(name = "requested_resource_id")
    public Long getRequestedResourceId()
    {
        return this.requestedResourceId;
    }

    public void setRequestedResourceId(final Long requestedResourceId)
    {
        this.requestedResourceId = requestedResourceId;
    }

    @Column(name = "requested_resource_name", nullable = false, length = 65535)
    public String getRequestedResourceName()
    {
        return this.requestedResourceName;
    }

    public void setRequestedResourceName(final String requestedResourceName)
    {
        this.requestedResourceName = requestedResourceName;
    }

    @Column(name = "priority", nullable = false)
    public short getPriority()
    {
        return this.priority;
    }

    public void setPriority(final short priority)
    {
        this.priority = priority;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "activity_last_updated", nullable = false, length = 19)
    public Date getActivityLastUpdated()
    {
        return this.activityLastUpdated;
    }

    public void setActivityLastUpdated(final Date activityLastUpdated)
    {
        this.activityLastUpdated = activityLastUpdated;
    }

    @Column(name = "assigned_rig_name", nullable = false, length = 65535)
    public String getAssignedRigName()
    {
        return this.assignedRigName;
    }

    public void setAssignedRigName(final String assignedRigName)
    {
        this.assignedRigName = assignedRigName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "assignment_time", nullable = false, length = 19)
    public Date getAssignmentTime()
    {
        return this.assignmentTime;
    }

    public void setAssignmentTime(final Date assignmentTime)
    {
        this.assignmentTime = assignmentTime;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(final boolean active)
    {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "removal_time", nullable = false, length = 19)
    public Date getRemovalTime()
    {
        return this.removalTime;
    }

    public void setRemovalTime(final Date removalTime)
    {
        this.removalTime = removalTime;
    }

    @Column(name = "removal_reason", nullable = false, length = 65535)
    public String getRemovalReason()
    {
        return this.removalReason;
    }

    public void setRemovalReason(final String removalReason)
    {
        this.removalReason = removalReason;
    }

    @Column(name = "code_reference", nullable = false, length = 65535)
    public String getCodeReference()
    {
        return this.codeReference;
    }

    public void setCodeReference(final String codeReference)
    {
        this.codeReference = codeReference;
    }

    @Column(name = "extensions", nullable = false)
    public short getExtensions()
    {
        return this.extensions;
    }

    public void setExtensions(final short extensions)
    {
        this.extensions = extensions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
    public Set<Rig> getRigs()
    {
        return this.rigs;
    }

    public void setRigs(final Set<Rig> rigs)
    {
        this.rigs = rigs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
    public Set<Rig> getRigs_1()
    {
        return this.rigs_1;
    }

    public void setRigs_1(final Set<Rig> rigs_1)
    {
        this.rigs_1 = rigs_1;
    }

}
