package au.edu.uts.eng.remotelabs.schedserver.dataaccess.entities;

// Generated 06/01/2010 5:09:20 PM by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAssociationId generated by hbm2java
 */
@Embeddable
public class UserAssociationId implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 2763184757998150139L;
    private long usersId;
    private long userClassId;

    public UserAssociationId()
    {
    }

    public UserAssociationId(final long usersId, final long userClassId)
    {
        this.usersId = usersId;
        this.userClassId = userClassId;
    }

    @Column(name = "users_id", nullable = false)
    public long getUsersId()
    {
        return this.usersId;
    }

    public void setUsersId(final long usersId)
    {
        this.usersId = usersId;
    }

    @Column(name = "user_class_id", nullable = false)
    public long getUserClassId()
    {
        return this.userClassId;
    }

    public void setUserClassId(final long userClassId)
    {
        this.userClassId = userClassId;
    }

    @Override
    public boolean equals(final Object other)
    {
        if ((this == other))
        {
            return true;
        }
        if ((other == null))
        {
            return false;
        }
        if (!(other instanceof UserAssociationId))
        {
            return false;
        }
        final UserAssociationId castOther = (UserAssociationId) other;

        return (this.getUsersId() == castOther.getUsersId())
                && (this.getUserClassId() == castOther.getUserClassId());
    }

    @Override
    public int hashCode()
    {
        int result = 17;

        result = 37 * result + (int) this.getUsersId();
        result = 37 * result + (int) this.getUserClassId();
        return result;
    }

}
