package au.edu.uts.eng.remotelabs.schedserver.dataaccess.entities;

// Generated 06/01/2010 5:09:20 PM by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserLock generated by hbm2java
 */
@Entity
@Table(name = "user_lock", catalog = "sahara")
public class UserLock implements java.io.Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = -7652820485119689900L;
    private Long id;
    private User user;
    private ResourcePermission resourcePermission;
    private boolean isLocked;
    private String lockKey;

    public UserLock()
    {
    }

    public UserLock(final User user,
            final ResourcePermission resourcePermission,
            final boolean isLocked, final String lockKey)
    {
        this.user = user;
        this.resourcePermission = resourcePermission;
        this.isLocked = isLocked;
        this.lockKey = lockKey;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(final Long id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser()
    {
        return this.user;
    }

    public void setUser(final User user)
    {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resource_permission_id", nullable = false)
    public ResourcePermission getResourcePermission()
    {
        return this.resourcePermission;
    }

    public void setResourcePermission(
            final ResourcePermission resourcePermission)
    {
        this.resourcePermission = resourcePermission;
    }

    @Column(name = "is_locked", nullable = false)
    public boolean isIsLocked()
    {
        return this.isLocked;
    }

    public void setIsLocked(final boolean isLocked)
    {
        this.isLocked = isLocked;
    }

    @Column(name = "lock_key", nullable = false, length = 50)
    public String getLockKey()
    {
        return this.lockKey;
    }

    public void setLockKey(final String lockKey)
    {
        this.lockKey = lockKey;
    }

}
